# Generated by Django 5.0.1 on 2024-02-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={
                "ordering": ["-id"],
                "verbose_name": "Shipping Address",
                "verbose_name_plural": "Shipping Addresses",
            },
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="full_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
