# Generated by Django 5.0.1 on 2024-02-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=250, unique=True, verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=99.99, max_digits=12, verbose_name="price"
            ),
        ),
    ]
