# Generated by Django 4.2.10 on 2024-02-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_options_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="images/products/default.png",
                upload_to="images/products/%Y/%m/%d",
            ),
        ),
    ]
